# Generated by Django 6.1.1 on 2026-09-29 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('high_level', '0002_alter_facture_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='operations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='high_level.operation'),
        ),
    ]
