# Generated by Django 6.1.1 on 2026-09-29 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('high_level', '0003_alter_produit_operations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='operation_suivante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='high_level.operation'),
        ),
    ]
